//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylon.BicycleStore.Rent.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daylon.BicycleStore.Rent.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand must be a valid enum value..
        /// </summary>
        public static string BICYCLE_BRAND_INVALID_ENUM {
            get {
                return ResourceManager.GetString("BICYCLE_BRAND_INVALID_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid brand is required..
        /// </summary>
        public static string BICYCLE_BRAND_REQUIRED {
            get {
                return ResourceManager.GetString("BICYCLE_BRAND_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color must be a valid enum value..
        /// </summary>
        public static string BICYCLE_COLOR_INVALID_ENUM {
            get {
                return ResourceManager.GetString("BICYCLE_COLOR_INVALID_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid color is required..
        /// </summary>
        public static string BICYCLE_COLOR_REQUIRED {
            get {
                return ResourceManager.GetString("BICYCLE_COLOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily rate must be greater than zero..
        /// </summary>
        public static string BICYCLE_DAILY_RATE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("BICYCLE_DAILY_RATE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle name is required..
        /// </summary>
        public static string BICYCLE_DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("BICYCLE_DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle name must not exceed 500 characters..
        /// </summary>
        public static string BICYCLE_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BICYCLE_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle ID is required..
        /// </summary>
        public static string BICYCLE_ID_EMPTY {
            get {
                return ResourceManager.GetString("BICYCLE_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle ID must be a valid GUID..
        /// </summary>
        public static string BICYCLE_ID_INVALID {
            get {
                return ResourceManager.GetString("BICYCLE_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model must be a valid enum value..
        /// </summary>
        public static string BICYCLE_MODEL_INVALID_ENUM {
            get {
                return ResourceManager.GetString("BICYCLE_MODEL_INVALID_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid model is required..
        /// </summary>
        public static string BICYCLE_MODEL_REQUIRED {
            get {
                return ResourceManager.GetString("BICYCLE_MODEL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle name is required..
        /// </summary>
        public static string BICYCLE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("BICYCLE_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle name must not exceed 100 characters..
        /// </summary>
        public static string BICYCLE_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BICYCLE_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero..
        /// </summary>
        public static string BICYCLE_PRICE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("BICYCLE_PRICE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be zero or greater..
        /// </summary>
        public static string BICYCLE_QUANTITY_ZERO_OR_GREATER {
            get {
                return ResourceManager.GetString("BICYCLE_QUANTITY_ZERO_OR_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental days must be greater than zero..
        /// </summary>
        public static string RENTAL_DAYS_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("RENTAL_DAYS_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental days must be greater than zero or null..
        /// </summary>
        public static string RENTAL_DAYS_GREATER_THAN_ZERO_OR_NULL {
            get {
                return ResourceManager.GetString("RENTAL_DAYS_GREATER_THAN_ZERO_OR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental days cannot exceed 90 days..
        /// </summary>
        public static string RENTAL_DAYS_MAX_LIMIT {
            get {
                return ResourceManager.GetString("RENTAL_DAYS_MAX_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental days must be at least 1 when both start and end dates are provided..
        /// </summary>
        public static string RENTAL_DAYS_MINIMUM_ONE {
            get {
                return ResourceManager.GetString("RENTAL_DAYS_MINIMUM_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra days must be at least 0 when both start and end dates are provided..
        /// </summary>
        public static string RENTAL_EXTRA_DAYS_MINIMUM_ZERO {
            get {
                return ResourceManager.GetString("RENTAL_EXTRA_DAYS_MINIMUM_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra days must be zero or greater..
        /// </summary>
        public static string RENTAL_EXTRA_DAYS_ZERO_OR_GREATER {
            get {
                return ResourceManager.GetString("RENTAL_EXTRA_DAYS_ZERO_OR_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method must be a valid enum value..
        /// </summary>
        public static string RENTAL_PAYMENT_METHOD_INVALID_ENUM {
            get {
                return ResourceManager.GetString("RENTAL_PAYMENT_METHOD_INVALID_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method is required..
        /// </summary>
        public static string RENTAL_PAYMENT_METHOD_REQUIRED {
            get {
                return ResourceManager.GetString("RENTAL_PAYMENT_METHOD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental start date must be in the future or null..
        /// </summary>
        public static string RENTAL_START_IN_FUTURE_OR_NULL {
            get {
                return ResourceManager.GetString("RENTAL_START_IN_FUTURE_OR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new date of birth must be different from the current one..
        /// </summary>
        public static string USER_DATE_OF_BIRTH_CANNOT_BE_SAME_AS_OLD {
            get {
                return ResourceManager.GetString("USER_DATE_OF_BIRTH_CANNOT_BE_SAME_AS_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required..
        /// </summary>
        public static string USER_DATE_OF_BIRTH_EMPTY {
            get {
                return ResourceManager.GetString("USER_DATE_OF_BIRTH_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth must be in the past..
        /// </summary>
        public static string USER_DATE_OF_BIRTH_IN_FUTURE {
            get {
                return ResourceManager.GetString("USER_DATE_OF_BIRTH_IN_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string USER_EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("USER_EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string USER_EMAIL_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("USER_EMAIL_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot exceed 256 characters..
        /// </summary>
        public static string USER_EMAIL_MAX_LENGTH {
            get {
                return ResourceManager.GetString("USER_EMAIL_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is required..
        /// </summary>
        public static string USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("USER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id must be a valid GUID..
        /// </summary>
        public static string USER_ID_INVALID {
            get {
                return ResourceManager.GetString("USER_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string USER_LAST_NAME_EMPTY {
            get {
                return ResourceManager.GetString("USER_LAST_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name can only contain letters and spaces..
        /// </summary>
        public static string USER_LAST_NAME_INVALID_CHARACTERS {
            get {
                return ResourceManager.GetString("USER_LAST_NAME_INVALID_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot exceed 100 characters..
        /// </summary>
        public static string USER_LAST_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("USER_LAST_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        public static string USER_NAME_EMPTY {
            get {
                return ResourceManager.GetString("USER_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can only contain letters and spaces..
        /// </summary>
        public static string USER_NAME_INVALID_CHARACTERS {
            get {
                return ResourceManager.GetString("USER_NAME_INVALID_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 100 characters..
        /// </summary>
        public static string USER_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("USER_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be the same as the old password..
        /// </summary>
        public static string USER_PASSWORD_CANNOT_BE_SAME_AS_OLD {
            get {
                return ResourceManager.GetString("USER_PASSWORD_CANNOT_BE_SAME_AS_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        public static string USER_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("USER_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot exceed 100 characters..
        /// </summary>
        public static string USER_PASSWORD_MAX_LENGTH {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        public static string USER_PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        public static string USER_PASSWORD_REQUIRE_LOWERCASE {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRE_LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        public static string USER_PASSWORD_REQUIRE_NUMBER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character..
        /// </summary>
        public static string USER_PASSWORD_REQUIRE_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRE_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        public static string USER_PASSWORD_REQUIRE_UPPERCASE {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRE_UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkow Error..
        /// </summary>
        public static string USER_UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("USER_UNKNOW_ERROR", resourceCulture);
            }
        }
    }
}
